import { GlobalProvider } from '@/Components/Global'
import Nav from '@/Components/Nav'
import Routes from '@/Components/Routes'
import Head from 'next/head'


export default function Home() {
  return (
    <GlobalProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Routes />
    </GlobalProvider>
  )
}
